
name: dbt_dremio
version: 1.0
config-version: 2

quoting:
  database: true
  schema: true
  identifier: true

macro-paths: ["macros"]

vars:
  default_materialization_database: '$scratch'
  default_materialization_schema: 'dbt.internal'
